# Generated by Django 2.2 on 2021-03-09 18:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
    ]
