# Generated by Django 2.2 on 2021-05-25 02:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corridas',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('capa', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
