# Generated by Django 2.2 on 2021-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluma', '0002_corridas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerovias',
            name='afectado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
